name: Laziness, Impatience, and Hubris
#description: Random noise
#meta_description: "Random noise"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 10
baseurl: /
domain_name: 'http://www.ivaturi.org'
google_analytics: 'UA-1223273-3'
permalink: pretty
gems:
    - jekyll-paginate
    - jekyll-gist

# Details for the RSS feed generator
url:            'http://www.ivaturi.org'
author:         'Aditya Ivaturi'
