name: Laziness, Impatience, and Hubris
#description: Random noise
#meta_description: "Random noise"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 10
baseurl: /
domain_name: 'http://www.ivaturi.org'
google_analytics: 'UA-1223273-3'

# Details for the RSS feed generator
url:            'blog url'
author:         'Aditya Ivaturi'
