name: Laziness, Impatience, and Hubris
#description: Random noise
#meta_description: "Random noise"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://www.ivaturi.org'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Aditya Ivaturi'
